### PR TITLE
Add support for shared option to MinGW builds generator

### PR DESCRIPTION
**Pull request by anton-matosov**

### CODE REVIEW

**Comment by anton-matosov** [comment]
You are welcome

**Comment by lasote** [comment]
I'm taking a look to the mingw-installer recipe to improve some things and push it to conan-center. It will require some minor changes in the package tools to (internally, not to the interface) so probably tomorrow will release a new version including these changes too. Thanks!

**Comment by lasote** [comment]
Released 0.5.4 with these changes and pointing to the mingw-installer in conan center. https://bintray.com/conan/conan-center

**Comment by anton-matosov** [comment]
That's great @lasote!
I have implemented pretty much the same stuff for MinGW installer here https://github.com/Dr-QP/conan-mingw-installer
I will switch to your implementation and will add couple PRs with minor fixes and improvements

**Pull request merged**
