### PR TITLE
Add support for GitHub Actions

### PR DESCRIPTION
**Pull request by Croydon**
Changelog: Feature: Add support for GitHub Actions 

Fixes https://github.com/conan-io/conan-package-tools/issues/474

### CODE REVIEW

**Comment by uilianries** [comment]
That's great! Thanks a lot @Croydon

**Comment by annulen** [comment]
Could you suggest any Conan recipe repository with multiplatform (i.e. different compilers, operating systems) build matrix which could be used as a template?

**Comment by Croydon** [comment]
At Bincrafters we use GitHub Actions only for Linux so far

You can see our template at https://github.com/bincrafters/templates/blob/32ab0bae69c58c3c842e4aba502687d9e9ccaebf/default/.github/workflows/conan.yml#L1

And see an example e.g. at https://github.com/bincrafters/conan-qt/actions or https://github.com/bincrafters/conan-cairo/actions

**Comment by annulen** [comment]
Thanks! msvc.yml and mingw.yml from Qt are particularly useful. My main use cases are:
* Replace AppVeyor for building MSVC and MinGW packages - GitHub Actions provides 20 concurrent builds for free, while AppVeyor only one, which makes building large packages like ICU quite painful. There is no image with VS2015, though I guess it should be possible to install it via chocolatey
* Build new recipe for Windows, Linux, and macOS and have all builds and configurations in the same place

**Comment by Croydon** [comment]
> There is no image with VS2015, though I guess it should be possible to install it via chocolatey

Regarding this, please consider upvoting https://github.com/actions/virtual-environments/issues/387

Installing VS2015 on the fly takes way too long

**Pull request merged**
