### PR TITLE
#308 Add CI Manager helper for commit id

### LINKED ISSUE #308: Provide commit id by CI Manager
Hi!

The class CIManager could offer commit id as a helper.

Regards!

### PR DESCRIPTION
**Pull request by uilianries**
closes #308

### CODE REVIEW

**Comment by lasote** [comment]
I'm ok with this but is there any specific use case or thing to document?

**Comment by uilianries** [comment]
For specific use case, when you run CPT for in-source cases where the author wants to run Conan for non-tags branches. As a branch could be named like "feature/foobar" we can't use the branch name directly as package version. 

Usually we use date (foo/20190111@bar/testing) to be easier to sort all packages when searching, but when you can have multiples PR per day, I think the best option is the sha (foo/abbe2a4@bar/testing).

This helper will get the commit checksum and it will be used as package version when not building a stable branch -- stable branch could be a tag, or even master branch (bleeding-edge).

**Comment by uilianries** [comment]
I've just rebased this branch to avoid a conflict from develop branch.

**Comment by lasote** [comment]
We would need to document it in the readme, and I would really like to see a use case explained there, like an example.

**Comment by uilianries** [comment]
Fair enough. I'll update soon.

**Comment by uilianries** [comment]
Done

**Pull request merged**
