### PR TITLE
Path to vcvarsall.bat was fixed for VS 2017

### PR DESCRIPTION
**Pull request by dmitry-zakablukov**
Path was changed from:
```
"%vs150comntools%../../VC/vcvarsall.bat"
```
to:
```
"%vs150comntools%../../VC/Auxiliary/Build/vcvarsall.bat"
```

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @dmitry-zakablukov,

I am trying to extend this fix to the conan ``tools.vcvars_command``, but I have an issue. The environment variable ``"%vs150comntools%`` is simply not defined, I have installed VS 2017 Community RC. How did you get such env-var defined? Is that working in your system? (Mine is Win 10, by the way). 

Thanks very much!

**Comment by KindDragon** [comment]
You can try this http://stackoverflow.com/a/41968736/61505 . IDK how do that in plain Python

**Comment by KindDragon** [comment]
Or you can create simple tool on C++ based on this sample (https://github.com/microsoft/vs-setup-samples) that will return pass to VS2017

**Comment by memsharded** [comment]
So far those two solutions seems very complicated, would be very costly to implement and especially costly to distribute and maintain. I prefer to keep things simple, so my proposal for this is to have the VS150comntools defined by the user, and just added the conditional for the new path and some checks. See https://github.com/conan-io/conan/pull/960

**Comment by memsharded** [comment]
@dmitry-zakablukov the funny thing is that ``vs150comntools`` actually exists if you are already running in the VS15 prompt. But in that case, you don't need to load the VS env-vars, they are already loaded, and in fact the ``tools.vcvars_command`` just check it. 

@lasote I think the same approach should be applied here in conan-package-tools.

**Comment by dmitry-zakablukov** [comment]
@memsharded , yes, I just defined VS150COMNTOOLS manually, as I always do when installing a new VS.

**Comment by memsharded** [comment]
@dmitry-zakablukov thanks, yes, that is the most pragmatic approach to this issue right now. I just added a check to ensure that users define it too.

**Pull request merged**
