### PR TITLE
commands almost all correct, but too many bugs exist in docker for windows

### PR DESCRIPTION
**Pull request by solvingj**
Do not merge this PR. 

This PR is just to demonstrate the most significant working changes that need to be made.  In the end, they turned out not to be too many, nothing fundamental.  Currently however, Conan Package Tools won't work with the current preview of Docker for Windows which supports simultaneous Windows and Linux containers.   Both container types fail run Conan/Conan Package Tools due to strange and separate errors which nobody seems to have a clue about. I tried both with python2 and python3. 

On the windows containers, to get to the error below, I had to use `set CONAN_DOCKER_IMAGE_SKIP_UPDATE=1`  because something about the PIP update step was corrupting the container and leaving it in an invalid state.  I had to revert the latest `docker commit` that package tools does to fix the container.   

For future reference, I plan to try rebuilding the images and retrying them again in a few weeks with future versions of Docker, and the Windows Core container insider builds. 

Wierd PIP dependency issue on Windows Containers. 
```
Profile created with detected settings: C:\Users\ContainerAdministrator\.conan\profiles\default
Traceback (most recent call last):
  File "C:\tools\python3\Scripts\run_create_in_docker-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 3088, in <module>
    @_call_aside
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\tools\python3\lib\site-packages\pkg_resources\__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography>=1.3.4; extra == "security"' distribution was not found and is required by requests
```

Wierd python create database issue in Linux Containers:
```
conan_runner
Traceback (most recent call last):
  File "/usr/local/bin/run_create_in_docker", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/conan/run_in_docker.py", line 9, in run
    runner = DockerTestPackageRunner.deserialize(the_json)
  File "/usr/local/lib/python2.7/dist-packages/conan/create_runner.py", line 230, in deserialize
    conan_pip_package=the_json["conan_pip_package"])
  File "/usr/local/lib/python2.7/dist-packages/conan/create_runner.py", line 40, in __init__
    self.conan_api, self.client_cache, self.user_io = Conan.factory()
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 167, in factory
    Version(MIN_SERVER_COMPATIBLE_VERSION))
  File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 128, in instance_remote_manager
    localdb = LocalDB(client_cache.localdb)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/store/localdb.py", line 13, in __init__
    self.init()
  File "/usr/local/lib/python2.7/dist-packages/conans/client/store/localdb.py", line 25, in init
    raise ConanException(message, e)
conans.errors.ConanException: ('Could not initialize local sqlite database', OperationalError('disk I/O error',))
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    builder.run()
  File "d:\sources\git-python\conan-package-tools\conan\packager.py", line 444, in run
    self.run_builds(profile_name=profile_name)
  File "d:\sources\git-python\conan-package-tools\conan\packager.py", line 496, in run_builds
    docker_entry_script=self.docker_entry_script)
  File "d:\sources\git-python\conan-package-tools\conan\create_runner.py", line 272, in run
    raise Exception("Error building: %s" % command)
Exception: Error building:  docker run --platform=linux --rm -v d:\sources\git-new\CMN\vs_base:/root/project -v C:\Users\jwiltse\.conan:/root/.conan -e CONAN_RUNNER_ENCODED="{\"args\": \"\", \"username\": \"bincrafters\", \"channel\": \"testing\", \"profile\": \"\ninclude(default)\n\n[settings]\narch=x86\nbuild_type=Release\ncompiler=gcc\ncompiler.version=4.8\nos=Linux\n[options]\n\n[env]\nCONAN_USER_HOME=/home/jenkins_conan_tmp/build_gcc_48\n[build_requires]\n\n\", \"conan_pip_package\": \"conan==1.2.3\", \"reference\": \"vs_base/0.1.0@bincrafters/testing\"}" -e CONAN_USERNAME=bincrafters -e CONAN_CHANNEL=testing -e CONAN_DOCKER_HOME="C:\users\me" -e CONAN_DOCKER_IMAGE="lasote/conangcc48" -e CONAN_DOCKER_PLATFORM="linux" -e CONAN_SKIP_CHECK_CREDENTIALS="True\" -e CONAN_UPLOAD="https://artifactory-test/artifactory/api/conan/conan-local" -e CONAN_UPLOAD_ONLY_WHEN_STABLE="" lasote/conangcc48 /bin/sh -c "cd /root/project && rm -f /root/.conan/profiles/default && (conan profile new default --detect || true) && run_create_in_docker"
```

Dockerfiles
Also strangely, I could not get the windows container to build successfully in a single pass.  I separated into multiple dockerfiles and it works.   I uploaded all the Dockerfiles used for creating the Windows images I tested with here:
https://github.com/solvingj/conan-docker-win-testing

### CODE REVIEW

**Comment by solvingj** [comment]
This was in relation to https://github.com/conan-io/conan-package-tools/issues/166

**Comment by lasote** [comment]
Thanks Jerry, let's start planning the refactor to the package tools to avoid as possible the conan home sharing and so on, I'm sure some of the problems are related with that fact.

**Comment by solvingj** [comment]
Yes, that's good.  I'd rather toss this out and re-do it in a better style. Also, I moved on to adding support for running linux docker containers inside of Windows Subsystem for Linux (WSL).  I ran into the same situation where the command string building is just a real unpleasant to reason about and refactor.

**Comment by solvingj** [comment]
Closing this in favor of the following:
https://github.com/conan-io/conan-package-tools/pull/221

No WSL support yet.

**Pull request closed without merging**
