### PR TITLE
Bamboo CI

### PR DESCRIPTION
**Pull request by marache**
Recognize Bamboo CI just like appveyor and travis are to set channel to "stable"

### CODE REVIEW

**Comment by lasote** [comment]
Thanks again! I don't know bamboo CI, I suppose it has a file like .travis.yml or appveyor.yml. Do you have an example to put it in the README?

**Comment by marache** [comment]
There isn't a configuration file, it's a proprietary CI tool developed by atlassian the makers of JIRA : https://www.atlassian.com/software/bamboo

**Comment by lasote** [comment]
Ok. Great. Could you write a line in the README? Just an "Bamboo integration" saying that Conan package tools also detects the branch on Bamboo CI to perform the Conan publish to a custom channel.

**Comment by marache** [comment]
Would this addition fit your description ?

**Comment by lasote** [comment]
Thanks! :)

**Pull request merged**
