### PR TITLE
Fix default libcxx for Clang build

### PR DESCRIPTION
**Pull request by uilianries**
Hey guys, I made a mistake with ctrl-c ctrl-v, sorry about that.

I just saw this issue in my Travis job, some minutes ago: https://travis-ci.org/uilianries/conan-catch/jobs/242799212

I'm trying to figure out how the tests passed successfully before.

### CODE REVIEW

**Comment by lasote** [comment]
No problem. I'll release a 0.4.1 right now.

**Comment by lasote** [comment]
Ready

**Comment by uilianries** [comment]
Thanks!

**Comment by uilianries** [comment]
Just a report, It's working now: https://travis-ci.org/uilianries/conan-catch/jobs/242826930

**Pull request merged**
