### PR TITLE
#339 Add Docker SELinux option

### PR DESCRIPTION
**Pull request by uilianries**
The docker selinux option will append :z to docker volume when calling `docker run -v`

Changelog: Feature: CPT supports SELinux (#339)
fixes: #339 

/cc @madebr 

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan-package-tools/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.

### CODE REVIEW

**Comment by madebr** [comment]
Tested on fedora 28 with enforcing selinux.

Imho, it would be a better user experience if selinux status would be detected automatically: https://howto.lintel.in/enable-disable-selinux-centos/

This is the output of `getenforce` on my machine:
```
$ getenforce
Enforcing
```
If I have disabled selinux, the output becomes:
```
$ getenforce
Permissive
```

**Comment by uilianries** [comment]
Yes, auto detection sound better.

I'll update this PR, thanks @madebr

**Comment by uilianries** [comment]
@madebr I think this is much simpler now.

**Comment by madebr** [comment]
Still works perfect!
Great job @uilianries !

**Comment by uilianries** [comment]
All conflicts are gone!

@lasote Could we release 0.25.1 with this fix?

**Comment by madebr** [comment]
I think this pr should be reopened for release/0.26

**Comment by uilianries** [comment]
@lasote why this PR is closed? It wasn't merged.

**Comment by lasote** [comment]
I really don't know :fearful:  probably it was closed during the release process when the remote branch was removed in favor of a tag. Please open it again to develop

**Pull request closed without merging**
