### PR TITLE
Implement the way to run some builds after upload

### PR DESCRIPTION
**Pull request by anton-matosov**
This is useful for toolchain packages when author wants build all variations in
the recipe, but doesn’t want to upload all the packages (e.g. to save some space
in the repo)

### CODE REVIEW

**Comment by lasote** [comment]
I'm not fully sure, I understand the goal but I think in most cases you want to know that all the packages are built ok before you upload something. I understand that, as we upload with --all, there is no other way to upload just some of the builds but I will think about it before merge this.

**Comment by lasote** [comment]
By the way, many many thanks for all this effort with mingw and package tools.

**Comment by anton-matosov** [comment]
You are very welcome.
Thank you guys for doing all that great job with conan package manager and its infrastructure.

You have very valid concern, I actually missed that point.
What I was trying to achieve is to try and build all the packages, but upload only some, not all.
My implementation is a kind of hacky, but is better than not building at all.
The proper way will be to extend `conan upload` to allow skipping some packages, or uploading specific list of packages. The complicated thing here is what should be passed as the argument. 

Another way I can think of is to actually pass 'upload/no_upload' flag to `conan create` so this way `conan upload` command will know which packages should be skipped

**Comment by lasote** [comment]
Yes, about the flag I was thinking about providing a flag upload/no upload to the build list. The problem is that we will need to:

- Change the package tools to directly use the conan python API (not documented, not stable yet). 
- Change conan to improve a little the Python API to be able to return the SHA of a created package
- Change the package tools to keep a list of build configuration => SHA and only upload the selected packages (the packages with the flag)

But there is still an additional problem, the builds that run inside a docker container, we would need a way to "return" the built IDs to the main process, and it's not an easy/clean task.

I would like much to improve package tools specially if we can call directly to the python api instead to the "conan" executable but not sure when we are going to be able to do it (0.27 at least) and how to resolve the docker problem.

**Pull request closed without merging**
