### PR TITLE
0.24.0

### PR DESCRIPTION
**Pull request by lasote**

### CODE REVIEW

**Comment by brianembry** [comment]
Please can we be better about releasing conan and CPT in sync when they become incompatible. 

```
 >> Conan/CPT version mismatch. Conan version installed: 1.13.0 . This version of CPT supports only Conan < 1.12
Traceback (most recent call last):
  File "build.py", line 23, in <module>
    builder.run()
  File "/usr/local/lib/python2.7/site-packages/cpt/packager.py", line 428, in run
    self._check_conan_version()
  File "/usr/local/lib/python2.7/site-packages/cpt/packager.py", line 295, in _check_conan_version
    raise Exception(msg)
Exception: Conan/CPT version mismatch. Conan version installed: 1.13.0 . This version of CPT supports only Conan < 1.12
```

**Comment by uilianries** [comment]
@lasote Here is the changelog for 0.24.0

Feature: Compatibility with Conan 1.13 (#341)
Feature: Support Shippable CI (#337)
Feature: Support Azure DevOps (#335)
Fix: Use the correct build path to load Conan class (#325)
Fix: Remove extra python requirements (#328)

**Comment by uilianries** [comment]
Hi @brianembry!

Sorry, we have a proper order to release the things. In fact CPT should be released first. However, you could use fixed versions to avoid any possible new bug in the future.

**Comment by lasote** [comment]
@brianembry that is the way we decided to operate. sorry. We are releasing first Conan and when everything is ready we release the compatible CPT. You should install CPT only in your build scripts to install the correct compatible conan.

**Comment by lasote** [comment]
Released.

**Pull request closed without merging**
