### PR TITLE
#339 Add Docker SELinux option

### PR DESCRIPTION
**Pull request by uilianries**
The docker selinux option will append :z to docker volume when calling `docker run -v`

Changelog: Feature: CPT supports SELinux (#339)
fixes: #339 

/cc @madebr 

Related PR: #360

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan-package-tools/blob/develop/.github/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.

### CODE REVIEW

**Comment by uilianries** [comment]
codecov is sad because we are not testing SE Linux. Well, I can't test it ...

Actually I could, but I would need to install SELinux in CentOS image, but I think it's not necessary. I'm not being lazy, I just think is too much effort to check it.

**Comment by madebr** [comment]
@uilianries You can add/create a `CONAN_FORCE_SELINUX`/`CONAN_SELINUX` environment variable. I don't think adding the `:z` argument to non-selinux systems is a problem.

**Comment by uilianries** [comment]
Excellent idea!

**Comment by madebr** [comment]
@uilianries Probably overkill, but you can also create a `getenforce` script on Linux that will simply print `Enforcing`.

**Comment by uilianries** [comment]
@madebr not needed, we can install selinux on Travis distro :)

**Pull request merged**
