### PR TITLE
Fix stable branch pattern regular expressions

### PR DESCRIPTION
**Pull request by ghost**
Changelog: (Fix): Fix regex patterns and move initialization to __init__() method

The first commit fixes the patterns by adding a `.` between the last character and the `*`.

The second commit moves the initialization of the `stable_branch_pattern` variable to the class' init method to reduce the code size and always assure an initialized value right from the start when the Packager is created. This change would also allow the use of multiple stable branch patterns when using the environment variable CONAN_STABLE_BRANCH_PATTERN.

All changes are backwards compatible.

Issue #557

- [X] Refer to the issue that supports this Pull Request.
- [X] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [X] I've read the [Contributing guide](https://github.com/conan-io/conan-package-tools/blob/develop/.github/CONTRIBUTING.md).
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.

### CODE REVIEW

**Comment by uilianries** [comment]
Thank you for your contribution. Just a new test to validate your main issue and we are good to merge.

**Comment by ghost** [comment]
It took a little longer than expected to add the tests.
All tests were passing locally on Ubuntu 18.04 / Python 3.6.
No idea why AppVeyor is failing, I thought it had been removed?

**Comment by ghost** [comment]
Is this an issue with how pull requests are configured in this project? I have multiple PRs that are already using GitHub actions in my fork. They are all failing in this repo because of the AppVeyor error.

**Comment by uilianries** [comment]
Weird error from Appveyor. Indeed we could move to Github Actions, or even to our internal Jenkins.

**Review by uilianries — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
