### PR TITLE
add os to generator settings

### PR DESCRIPTION
**Pull request by ericLemanissier**
the feature is already documented in the second example of https://github.com/conan-io/conan-package-tools#filtering-or-modifying-the-configurations, and allows to differentiate mingw from linux gcc.

Changelog: (Feature | Fix | Bugfix): Describe here your pull request

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [X] I've read the [Contributing guide](https://github.com/conan-io/conan-package-tools/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
@uilianries @lasote what do you think  of this PR ?

**Comment by uilianries** [comment]
Hi @ericLemanissier, why do you need it? so far I don't remember any problems related to the OS

**Comment by ericLemanissier** [comment]
I don't remember the exact case where I needed, this feature, but the second example of https://github.com/conan-io/conan-package-tools#filtering-or-modifying-the-configurations is relevant:
```
from cpt.packager import ConanMultiPackager

builder = ConanMultiPackager(username="myuser")
builder.add_common_builds()
builder.update_build_if(lambda build: build.settings["os"] == "Windows",
                        new_build_requires={"*": ["7zip_installer/0.1.0@conan/stable"]})
# Also avaiable parameters:
#    new_settings, new_options, new_env_vars, new_build_requires, new_reference
```
This cannot work currently, because build.settings does not have an `"os"` key, it only has `"arch"`, `"build_type"`, `"compiler"`, `"compiler.version"` keys

**Comment by uilianries** [comment]
I think it's related to the issue https://github.com/conan-io/conan-package-tools/issues/40

**Comment by ericLemanissier** [comment]
I don't have the need for this any more

**Pull request closed without merging**
