### PR TITLE
build static before shared

### PR DESCRIPTION
**Pull request by ericLemanissier**
usually, the static build is the default one

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [X] I've read the [Contributing guide](https://github.com/conan-io/conan-package-tools/blob/develop/.github/CONTRIBUTING.md).
- [X] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Before I go spend time fixing unit tests, What do you think of this change @uilianries ?

**Comment by uilianries** [comment]
I don't see any advantage. Why do you need that, besides the fact `shared=False` is the default for most of recipes?

**Comment by ericLemanissier** [comment]
It's not "needed" per se.it makes the default config available earlier, which allows starting dependants earlier, especially in case of network error/ci timeout etc.

**Comment by uilianries** [comment]
Okay, go ahead. I gonna work on CPT today and tomorrow, we can include it together.

**Review by Croydon — APPROVED** [review]
LGTM

I think it makes sense if we mimic the build order of CCI as close as possible. This is a step towards this

**Comment by uilianries** [comment]
Yes, thanks for pinging. I forgot this one, let's continue this week.

**Review by danimtb — APPROVED** [review]

**Review by uilianries — APPROVED** [review]
LGTM

**Pull request merged**
