### PR TITLE
Add GitHub settings

### PR DESCRIPTION
**Pull request by uilianries**
- Use standard Conan tags for CPT issues
- Add stale config file to timeout bot
- Add issue template

NOTE: The target branch is **master** because it is not a feature be release on the next version.

### CODE REVIEW

**Comment by danimtb** [comment]
Are the tags extracted from the docs repo? those are the settings we should use to homogenize them

**Comment by uilianries** [comment]
I've extract from conan-io/conan

**Comment by danimtb** [comment]
conan-io/conan does not have a *.github/settings.yml* file

**Comment by uilianries** [comment]
so it was from conan-community/community

**Comment by danimtb** [comment]
Use the one from the docs please

**Comment by uilianries** [comment]
> Use the one from the docs please

Done!

**Pull request merged**
