### PR TITLE
azure pipelines support

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Azure pipelines always checks out in detached head state, so the GenericManager is not able to identify the branch, which leads to wrong conan channel

**Comment by uilianries** [comment]
BTW, the predefined env vars are here: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops

**Comment by ericLemanissier** [comment]
Yes, unfortunately there is no AZUREPIPELINES env var, as for travis and appveyor. I use SYSTEM_TEAMFOUNDATIONCOLLECTIONURI as a replacement, but maybe it's not the best choice ?

**Comment by uilianries** [comment]
Use what works for CPT. If `SYSTEM_TEAMFOUNDATIONCOLLECTIONURI` is working for Azure, let's keep it.

**Pull request merged**
