### PR TITLE
Make '--all' argument conditional for conan upload

### PR DESCRIPTION
**Pull request by jgsogo**
Let the upload method have an argument to select whether to upload all, recipe + package, or only recipe. 

Motto: https://github.com/conan-io/conan-package-tools/issues/25

### CODE REVIEW

**Comment by jgsogo** [comment]
This argument could be taken from environment, overriden using a child class ([here](https://github.com/jgsogo/conan-portaudio/pull/2)), set in constructor,... what do you think about it?

**Comment by memsharded** [comment]
Here is what I do if I don't want to upload the created binaries, only the package recipe: I disable upload at all, and just upload the recipe manually from my command line. I wonder if some of the upload to S3 failures in CI could be because of concurrent uploads of the package recipe to S3. 

Not a huge pain, be maybe having some way to upload only the recipe as this PR suggests, could be useful.

**Comment by lasote** [comment]
Hi, the @memsharded way is valid, but if you want to control it with an environment variable it's ok for me. Just complete the PR doing:

- Create a new parameter in ConanMultiPackager constructor called "upload_only_recipe" with default False
- Assign to self.upload_only_recipe in the constructor reading the parameter and the CONAN_UPLOAD_ONLY_RECIPE environment variable
- Control the upload all reading self.upload_only_recipe
- Document the new env variable in the Readme

**Comment by Croydon** [comment]
@jgsogo Ping.

I think this is still useful for complete tests on master pushes without actually uploading all the packages.

**Comment by lasote** [comment]
I think this can be closed. Now the conan_api is used and the json return also to know which packages to upload.

**Pull request closed without merging**
